server:
  port: 8081
spring:
  datasource:
    password: Sampathkatkam
    url: jdbc:mysql://localhost:3306/jrtpmini02
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    password: gxpr jmga wrrd zcxb
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: sampathkatkam785@gmail.com
    
    
app:
  messages:
   dupEmail: Duplicate Email address
   invalidcredential: Invalid Credentials..
   